name: Build & Deploy Application

on:
  push:
    tags:
      - "**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout the project
        uses: actions/checkout@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ secrets.BASE_URL_PROD }}/pdf-service
          flavor: |
            latest=false
          tags: |
            type=semver,pattern={{raw}}
      - 
        name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.BASE_URL_PROD }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - 
        name: Build and push to the registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
